---
- hosts: all
  vars:
    packages:
      RedHat:
        - tree
        - vim 
        - tmux
  roles:
    - role: '{{playbook_dir}}'
  

- hosts: localhost
  roles:
    - role: '{{playbook_dir}}'
