---
- name: "add vscode source"
  block:
    - name: apt-key > add an Apt signing microsoft key
      become: True
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        keyring: /etc/apt/keyrings/packages.microsoft.gpg
        state: present

    - name: apt-repo > microsoft apt source repo
      become: True
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.gpg]
          https://packages.microsoft.com/repos/code stable main
        filename: vscode
        state: present

- name: "add typora source"
  block:
    - name: apt-key > add an Apt signing typora key
      become: True
      ansible.builtin.apt_key:
        url: https://typora.io/linux/public-key.asc
        # file: /etc/apt/trusted.gpg.d/typora.asc
        state: present

    - name: apt-repo > typora apt source repo
      become: True
      ansible.builtin.apt_repository:
        repo: >
          deb https://typora.io/linux ./
        filename: typora
        state: present

- name: "apt-get> install desktop packages"
  become: True
  apt:
    update_cache: True
    name: "{{ item }}"
    state: present
  with_items: "{{ packages.UbuntuDesktop }}"
  when: ansible_os_family=="Debian"

- name: "terminator> copy config"
  copy:
   src: terminator/config
   dest: ~/.config/terminator/config

# maybe install chome?
- name: "shell> add line to change browser"
  lineinfile:
    path: "{{ item }}"
    line: "export BROWSER=google-chrome"
    create: True
  with_items:
     - ~/.zshrc
     - ~/.bashrc

# install headlamp app image
- name: "appimage> download headlamp"
  uri:
    url: https://github.com/kubernetes-sigs/headlamp/releases/download/v0.35.0/Headlamp-0.35.0-linux-arm64.AppImage
    dest: ~/appimage/Headlamp
    chmod: 0755

- name: "appimage> copy desctop file"
  copy:
   src: Headlamp.desktop
   dest: ~/.local/share/application/Headlamp.desktop

- name: "appimage> install icon"
  become: true
  shell: |
    desktop-file-install ~/.local/share/applications/Headlamp.desktop
