---
# tasks file for ansible-dot-files

- name: "honebrew> install dependences"
  homebrew:
     name: "{{ item }}"
     state: present
  with_items: "{{ packages.MacOS }}"
  when: ansible_os_family=="Darwin" 

- name: "apt-get> install dependences"
  become: True
  apt:
    update_cache: True
    name: "{{ item }}"
    state: present
  with_items: "{{ packages.Ubuntu }}"
  when: ansible_os_family=="Debian"

- name: "yum> install dependences"
  become: True
  yum:
    update_cache: True
    name: "{{ item }}"
    state: present
  with_items: "{{ packages.RedHat }}"
  when: ansible_os_family=="RedHat"


- name: "vim> copy config file"
  copy:
   src: .vimrc
   dest: ~/.vimrc

- name: "ansible> template config file"
  template:
   src: ansible.cfg.j2
   dest: ~/.ansible.cfg

- name: "git> set config"
  git_config:
     name: core.editor 
     scope: global
     value: vim 

- name: "shell> add line to change editor"
  lineinfile:
    path: "{{ item }}"
    line: "export EDITOR=vim"
    create: True
  with_items:
     - ~/.zshrc
     - ~/.bashrc

