---
# tasks file for ansible-dot-files

- name: "honebrew> install dependences"
  homebrew:
     name: "{{ item }}"
     state: present
  with_items:
       - vim
       - ranger 
       - tmux 
  when: ansible_os_family=="Darwin" 

- name: "vim> copy config file"
  copy:
   src: .vimrc
   dest: ~/.vimrc

- name: "ansible> template config file"
  template:
   src: ansible.cfg.j2
   dest: ~/.ansible.cfg
