---
# tasks file for ansible-dot-files
- name: "vim> copy config file"
  copy:
   src: .vimrc
   dest: ~/.vimrc

- name: "ansible> template config file"
  template:
   src: ansible.cfg.j2
   dest: ~/.ansible.cfg
